### PR TITLE
Added v!support and support to help command

### PR DESCRIPTION
**Pull request by Kalissaac**

### CODE REVIEW

**Comment by Kalissaac** [comment]
upload your public key

**Comment by Kalissaac** [comment]
wait no dont merge this yet, I forgot about slash commands so stuff may break

**Review by MomoMiles — COMMENTED** [review]
Looks all good. Sorry I was so late on this. Push it if you need it still.

**Comment by MomoMiles** [comment]
Just saw this. Keep it closed 👍

**Pull request closed without merging**
