### PR TITLE
Version 1.4.0

### PR DESCRIPTION
**Pull request by Kalissaac**
Long overdue release. Is 1.4.0 an appropriate version?

### CODE REVIEW

**Review by MomoMiles — APPROVED** [review]
Looks all good

**Comment by Kalissaac** [comment]
Fantastic, I'll write the changelog and then we'll merge.

**Comment by Kalissaac** [comment]
# Changelog

## BREAKING CHANGES
`botAdminCollectionTransfer` is now removed. If you are upgrading from a version before 1.3.0, please do an incremental upgrade to there before upgrading to 1.4.0 or later.

## Added Features
* DM players who are not in the voice channel when the match starts
* Players can now switch between teams without unreacting
* Team player limit can now be set in `constants.js`
* Added Icebox as a map
* Lots of documentation added, autocomplete now works in 90% of the codebase

## Bug Fixes
* Usernames are now validated
* Environment variables are now verified upon startup

**Comment by Kalissaac** [comment]
@MomoMiles do you think this release warrants a 2.0.0 version jump?

**Pull request merged**
